### ISSUE TITLE
Livery not Loading

### ISSUE THREAD

**Issue by Gamer1029384756** [kolos26/GEOFS-LiverySelector#353]
the liveries are not loading and it is not possible to scroll through the liveries.

**Comment by kolos26** [comment]
Sorry about that, GeoFs 3.6 is just out, and it's really chaotic now. It should be fixed in a few days.

**Comment by Gamer1029384756** [comment]
The liveries are loading now but it is still not possible to scroll through the liveries.

**Comment by kolos26** [comment]
I have fixed the bug. Please update LiverySelector.
[https://github.com/kolos26/GEOFS-LiverySelector/releases/tag/v2.0.3](https://github.com/kolos26/GEOFS-LiverySelector/releases/tag/v2.0.3)
Thank you for using LiverySelector!
Kolos26
